### ISSUE TITLE
Not working on Opera GX both browser and side bar

### ISSUE THREAD

**Issue by SleeptMooN** [Arcus92/instagram-video-control#47] opened 2024-10-25 13:27 UTC
Hey there, I love this extension and it's been working wonders for the past few years but it stopped working as of recently, I'm using it in Opera GX and have been for several years but it just stopped working both in the instagram site or the sidebar instagram that opera has.

If you could take a look at it, I would be appreciate it, as the 100% volume in reels all the time kills my ears.. and no extension is currrently working either, maybe it is something to do with instagram updating ?

**Comment by Arcus92** [comment] 2024-10-25 19:18
Hi @SleeptMooN,
This is the second report of Opera GX been broken. It is working fine in Firefox and Chrome so far.
I'll setup a virtual machine and investigate the case.

**Comment by Arcus92** [comment] 2024-10-25 20:28
I couldn't reproduce it on a fresh Win 11 VM with Opera GX 114.0.52.82.123. I tested posts and reals in the main window and the sidebar. 

I noticed another issue: After the video loops the main area shows a still frame and overlays the video. This also happens on Chrome but not on Firefox.

**Comment by Arcus92** [comment] 2024-10-26 10:16
The older post was re-opened. I'll close this one. Please continue the discussion in #46

**Closed by Arcus92** 2024-10-26 10:16 UTC
Labels: bug
