### ISSUE TITLE
Can't use controls because of comment/reply section on top

### ISSUE THREAD

**Issue by back2Lobby** [Arcus92/instagram-video-control#16] opened 2024-03-24 01:33 UTC
In stories, we can't use the media controls because it's behind the reply section. I have attached a video demonstrating the issue.
Maybe moving the media controls a little bit up can solve it.

https://github.com/Arcus92/instagram-video-control/assets/29447722/fe2e2831-b74c-446f-95e2-601dfd82229c

**Comment by Arcus92** [comment] 2024-03-24 11:06
Thanks for reporting.
I already found the cause. I'll need to change the detection method for Stories.

**Comment by Arcus92** [comment] 2024-03-25 22:04
Update the main issue was solved with v1.0.1 - in Desktop mode. 
However, when shrinking you browser window to almost mobile size Instagram will apply another layout. This layout breaks my changes. I'll keep working on this issue.

**Comment by back2Lobby** [comment] 2024-03-25 23:45
> Update: the main issue was solved with v1.0.1 - in Desktop mode. However, when shrinking you browser window to almost mobile size Instagram will apply another layout. This layout breaks my changes. I'll keep working on this issue.

That's great! 😍

Just to clear confusion, the video I posted (in this issue) was not on any resized browsed window, I just cropped it after recording to highlight main issue easily. On top of that, feels weird when a desktop browser extension works for mobile view also lol 😁.

You solved this one pretty quick tbh, Thanks a lot! 💖

**Comment by Arcus92** [comment] 2024-03-26 21:56
Mobile or "small browser window" Story-mode should be fixed by #21 in v1.0.2.

**Closed** 2024-03-26 21:57 UTC
Labels: bug
